const AUTH_ACTION_TYPES = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  REFRESH_REQUEST: 'REFRESH_REQUEST',

  AUTH_REQUEST_SUCCESS: 'AUTH_REQUEST_SUCCESS',
  AUTH_REQUEST_FAIL: 'AUTH_REQUEST_FAIL',
};

export default AUTH_ACTION_TYPES;
